### PR TITLE
Release/1.0.0

### PR DESCRIPTION
**Pull request by KarmaKamikaze**

### CODE REVIEW

**Review by mirakst — DISMISSED** [review]
lgtm

**Review by damniko — APPROVED** [review]
Lang men meget underholdende. Glæder mig til at læse 2'eren!

**Review by mirakst — APPROVED** [review]
good first issue

**Review by Sarmisuper — APPROVED** [review]
LGTM

**Review by selectionator — APPROVED** [review]
I approve of this release and condemn every merge conflict to the boiler room of hell

**Review by KasperHenningsen — APPROVED** [review]

**Pull request merged**
